[[redirects]]
  from = "/1-thang-lam-dep-hieu-qua-de-co-khuon-mat-dep-nhu-mo"
  to = "/"
  status = 200
  force = true

[[redirects]]
  from = "/highlands-voucher-page.html"
  to = "/khuyen-mai-highlands-uu-dai-highlands-voucher-highlands"
  status = 200
  force = true  